/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProjectController; // Importa o controlador ProjectController
import Controller.taskController; // Importa o controlador taskController
import java.awt.Color; // Importa a classe Color para manipulação de cores no ambiente gráfico
import java.awt.Font; // Importa a classe Font para manipulação de estilos de fonte no ambiente gráfico
import Model.Project; // Modelo Project
import Model.Task; // Modelo Task
import java.awt.event.WindowAdapter; // Importa a classe WindowAdapter para lidar com eventos de janela
import java.awt.event.WindowEvent; // Importa a classe WindowEvent para eventos de janela
import java.util.List; // Importa a interface List do Java
import javax.swing.DefaultListModel; // Importa a classe DefaultListModel para construção visual de componentes
import util.TaskTableModel; // Importa a classe TaskTableModel para criação manual de uma construção virtual
import util.deadLimeColon; // Importa a classe deadLimeColon para manipulação de colunas



/**
 * MainJframe vai ser usado como tela principal da aplicação, nela vai conter a parte
   visual, e trecho de códigos colocados manualmente, já que existe essa possibilidade já estamos usando o dragon

 */
public final class MainJFrame extends javax.swing.JFrame {
    
    // criação das variáveis porém não iniciando elas
                   //criação dos dois controles
        ProjectController projectcontroller; 
        taskController TaskController;
        // esse objeto tá vinculado com o jlist e serve para ser expecificado o que vai ser mostrado
        DefaultListModel projectsModel; //o defaultlistmodel vai guardar os objetos para ser exibido 
        TaskTableModel taskModel;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() { //o construtor
        // Inicializa os componentes visuais definidos no arquivo de design da GUI.
        initComponents();

        // Inicializa o controlador de dados. Este método provavelmente configura a lógica de controle para a manipulação de dados.
        initDataController();

        // Inicializa o modelo dos componentes (possivelmente modelos de dados para exibição em tabelas, listas, etc.).
        initComponetModel();

        // Configura a decoração (provavelmente o estilo ou formatação) da tabela de tarefas.
        decorateTableTask();

       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEmptyList = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tobar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tobartiton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tobarsubtiton = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1Taks = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jPanelEmptyList.setBackground(java.awt.Color.white);

        jLabel8.setBackground(new java.awt.Color(204, 0, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nenhuma tarefa por aqui");

        jLabel10.setBackground(new java.awt.Color(204, 0, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Clique no mais para adicionar uma tarefa");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        javax.swing.GroupLayout jPanelEmptyListLayout = new javax.swing.GroupLayout(jPanelEmptyList);
        jPanelEmptyList.setLayout(jPanelEmptyListLayout);
        jPanelEmptyListLayout.setHorizontalGroup(
            jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelEmptyListLayout.setVerticalGroup(
            jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 102));
        setMinimumSize(new java.awt.Dimension(600, 600));

        tobar.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        jLabel1.setText("Todo app");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Anote tudo aqui, n]ao esqueça de nada");

        javax.swing.GroupLayout tobarLayout = new javax.swing.GroupLayout(tobar);
        tobar.setLayout(tobarLayout);
        tobarLayout.setHorizontalGroup(
            tobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tobarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tobarLayout.setVerticalGroup(
            tobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tobarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        tobartiton.setBackground(new java.awt.Color(255, 255, 255));
        tobartiton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("Tarefas");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tobartitonLayout = new javax.swing.GroupLayout(tobartiton);
        tobartiton.setLayout(tobartitonLayout);
        tobartitonLayout.setHorizontalGroup(
            tobartitonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tobartitonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        tobartitonLayout.setVerticalGroup(
            tobartitonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tobartitonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tobartitonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        tobarsubtiton.setBackground(new java.awt.Color(255, 255, 255));
        tobarsubtiton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jList1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFixedCellHeight(50);
        jList1.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout tobarsubtitonLayout = new javax.swing.GroupLayout(tobarsubtiton);
        tobarsubtiton.setLayout(tobarsubtitonLayout);
        tobarsubtitonLayout.setHorizontalGroup(
            tobarsubtitonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tobarsubtitonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        tobarsubtitonLayout.setVerticalGroup(
            tobarsubtitonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tobarsubtitonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(8, 8, 8))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1Taks.setAutoCreateRowSorter(true);
        jTable1Taks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1Taks.setForeground(new java.awt.Color(0, 0, 0));
        jTable1Taks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1Taks.setToolTipText("");
        jTable1Taks.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jTable1Taks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1Taks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1Taks.setShowVerticalLines(true);
        jTable1Taks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1TaksMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1Taks);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 102));
        jLabel5.setText("Projetos");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tobarsubtiton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tobartiton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tobartiton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tobarsubtiton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
                // evento de click mouse para abrir a janela projectDialog
                
                Projectdialogscrenn Projectdialogscrenn = new Projectdialogscrenn(this, rootPaneCheckingEnabled);
                Projectdialogscrenn.setVisible(true); //foi usado um setVisible com o paramentro true para mostrar a janela
                
               Projectdialogscrenn.addWindowListener(new WindowAdapter(){ //o Window liste ouve as ações da janela, nesse caso ela usa o window adapter para definir quais as proximas ações
               public void windowClosed(WindowEvent e){ //o window adapter localizou o windowClosed
               loadProjects(); //faz o carregamento dos dados, de forma atualizada
                
               }});
                
    }//GEN-LAST:event_jLabel9MouseClicked
   // abrir a janela e fazer ação quando fechar a janela de tarefa.
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        TarefaDialogscrenn taskDialogSreen = new TarefaDialogscrenn(this, rootPaneCheckingEnabled);
        int projectIndex = jList1.getSelectedIndex(); //retorna o indice do item selecionado.
        Project project = (Project)projectsModel.get(projectIndex);
        taskDialogSreen.setProject(project);
        
        taskDialogSreen.setVisible(true);
        
     
        taskDialogSreen.addWindowListener(new WindowAdapter(){
        @Override
        public void windowClosed(WindowEvent e){
        
        int projectIndex = jList1.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        loadTasks(project.getId());
        
               }});
        
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTable1TaksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1TaksMouseClicked
 //check
        int rowIndex = jTable1Taks.rowAtPoint(evt.getPoint());
       int columnIndex = jTable1Taks.columnAtPoint(evt.getPoint());
       
        switch (columnIndex) {
            case 3 -> {
                Task task = taskModel.getTasks().get(rowIndex);
                TaskController.update(task);
                }
                }
     
        
     
    }//GEN-LAST:event_jTable1TaksMouseClicked
//select
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        int projectIndex = jList1.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        loadTasks(project.getId());
        
        
        
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEmptyList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1Taks;
    private javax.swing.JPanel tobar;
    private javax.swing.JPanel tobarsubtiton;
    private javax.swing.JPanel tobartiton;
    // End of variables declaration//GEN-END:variables
/*-------------------------------------------
    método para fazer a decorete da table task, fazendo a módificação 
    da font, e fundo, definir se quer ou não linhas na table
  */  
public void decorateTableTask(){
    
    //Customizando o hader
    //usando o método getTableHeader para setar
    jTable1Taks.getTableHeader().setFont(new Font("Segoe UE", Font.BOLD, 14));
    jTable1Taks.getTableHeader().setBackground(new Color(0,153,102));
    jTable1Taks.getTableHeader().setForeground(new Color(255,255,255));
    //ordem
    jTable1Taks.setAutoCreateRowSorter(true);
    
    /*Pego a jtable > puxo a informação das colunas> puxo a informação de que tem na coluna 2
    > setor a informação com o setCellRenderer(e digo que é para criar de acordo ocm o deadLine*/
    jTable1Taks.getColumnModel().getColumn(2).setCellRenderer(new deadLimeColon()); 
}
//-----------------------------------------------------
            public void initDataController(){ // method for created class
                   projectcontroller = new ProjectController();
                   TaskController = new taskController();}
//-----------------------------------------------------           
            public void initComponetModel(){
                projectsModel = new DefaultListModel();
                loadProjects(); //carregando o projeto do metodo 447
                
                taskModel = new TaskTableModel(); // vai ser iniciado com o construtor esse objeto da classe moddel
                jTable1Taks.setModel(taskModel); //setando o model util que foi criando para mostra o task model

                }
             
            
 //-----------------------------------------------------           
                public void loadTasks(int Project) {
                    // Método para carregar os dados do banco de dados
                    List<Task> tasks = TaskController.getAll(Project); // Criação de uma lista com a variável tasks, chamando o método getAll
                    taskModel.setTasks(tasks); // Carregar as tarefas dentro de taskmodel

                    System.out.println("Is tasks empty? " + tasks.isEmpty());
                     showJTableTasks(!tasks.isEmpty());
                }
 //-----------------------------------------------------           
          private void showJTableTasks(boolean hasTasks){
                if(hasTasks){
                        //Existem tarefas.
                    if(jPanelEmptyList.isVisible()){
                        jPanelEmptyList.setVisible(false);
                        jPanel4.remove(jPanelEmptyList);
                    }
                    
                    jPanel4.add(jScrollPane2);
                    jScrollPane2.setVisible(true);
                    jPanel4.setSize(jPanel4.getWidth(), jPanel4.getHeight());
                    
                }else 
                {if (jScrollPane2.isVisible()){
                    jScrollPane2.setVisible(false);
                    jPanelEmptyList.setSize(jPanel4.getWidth(), jPanel4.getHeight());
                }
               jPanel4.add(jPanelEmptyList);
               jPanelEmptyList.setVisible(true);
               jPanelEmptyList.setSize(jPanel4.getWidth(),jPanel4.getHeight());
                    
                }
            }
          
//-----------------------------------------------------      
          
            public void loadProjects(){
                List<Project> projects = projectcontroller.getAll(); //lista de projeto
                projectsModel.clear(); // limpar os dados do model, caso tenha.
                for (int i = 0; i < projects.size(); i++) { // For para ir pegando todas as informações do banco de dados.
                    Project project = projects.get(i); //puxa as informações e joga para o objeto que tem o tipo project, nele tem armazenado os elementos
                projectsModel.addElement(project); // usando o model para adicionar a lista de cada loop.
                }
                jList1.setModel(projectsModel); // vinculuar a visualização do projectModel para o Jlist 
            }
                   
                   
            
                   
                   
            

}